### ISSUE TITLE
How can I use the model to infer in my data?

### ISSUE THREAD

**Issue by Lambru99** [Xinhao-Deng/Website-Fingerprinting-Library#4]
I trained and tested the DF model with the CW dataset, with the DF.sh script. It gives me this log:
```json
{
    "Accuracy": 0.9836,
    "Precision": 0.9844,
    "Recall": 0.9836,
    "F1-score": 0.9837
}
```
How can I use the model to infer my data? In other words, it is possible to prove this model by trying to correlate my user by the fingerprint using my pcap? Where is stored the model?

**Comment by Xinhao-Deng** [comment]
The saved model path is located at `checkpoints/CW/DF`. If you want to use the DF model to infer your own traffic, you need to extract the packet direction sequence from the pcap file and input it into the model. 

In fact, you cannot directly use the DF model trained on the CW dataset to infer other data. The reason is that the CW dataset is intended for research purposes only, and the model's output consists of meaningless numbers, with each number representing an anonymized domain name. Therefore, no useful information can be extracted from the model's numeric output.

**Comment by Lambru99** [comment]
> The reason is that the CW dataset is intended for research purposes only, and the model's output consists of meaningless numbers

Is this thing for all the models propose on your repo or just for DF?

**Comment by Xinhao-Deng** [comment]
All methods and datasets are intended for research purposes only.
